// Arquivo: frontend/interfaces/user.ts
export interface User {
    id: string;
    aud?: string;
    role?: string;
    email?: string;
    encrypted_password?: string;
    email_confirmed_at?: string;
    confirmation_token?: string;
    confirmation_sent_at?: string;
    recovery_token?: string;
    recovery_sent_at?: string;
    email_change_token_new?: string;
    email_change?: string;
    email_change_sent_at?: string;
    last_sign_in_at?: string;
    is_super_admin?: boolean
    created_at?: string;
    updated_at?: string;
    phone: string;
    phone_confirmed_at?: string;
    phone_change?: string;
    phone_change_token?: string;
    phone_change_sent_at?: string;
    confirmed_at?: string;
    email_change_token_current?: string;
    email_change_confirm_status?: string;
    banned_until?: string;
    reauthentication_token?: string;
    reauthentication_sent_at?: string;
    is_sso_user?: boolean;
    deleted_at?: string;
    is_anonymous?: boolean;
    empresa_id?: string;
    filial_id?: string;
    nome: string;
    cidade: string;
    uf: string;
  }